# Generated by Django 3.0.2 on 2020-02-02 22:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('l1', 'Andaman and Nicobar Islands'), ('l2', 'Andhra Pradesh'), ('l3', 'Arunachal Pradesh'), ('l4', 'Assam'), ('l5', 'Bihar'), ('l6', 'Chandigarh'), ('l7', 'Chhattisgarh'), ('l8', 'Dadra and Nagar Haveli and Daman and Diu'), ('l9', 'Delhi'), ('l10', 'Goa'), ('l11', 'Gujarat'), ('l12', 'Haryana'), ('l13', 'Himachal Pradesh'), ('l14', 'Jammu and Kashmir'), ('l15', 'Jharkhand'), ('l16', 'Karnataka'), ('l17', 'Kerala'), ('l18', 'Ladakh'), ('l19', 'Lakshadweep'), ('l20', 'Madhya Pradesh'), ('l21', 'Maharashtra'), ('l22', 'Manipur'), ('l23', 'Meghalaya'), ('l24', 'Mizoram'), ('l25', 'Nagaland'), ('l26', 'Odisha'), ('l27', 'Puducherry'), ('l28', 'Punjab'), ('l29', 'Rajasthan'), ('l30', 'Sikkim'), ('l31', 'Tamil Nadu'), ('l32', 'Telangana'), ('l33', 'Tripura'), ('l34', 'Uttar Pradesh'), ('l35', 'Uttarakhand'), ('l36', 'West Bengal')], max_length=50)),
                ('total_students', models.IntegerField(default=1)),
                ('stream', multiselectfield.db.fields.MultiSelectField(choices=[('engg', 'Engineering'), ('mgmt', 'Management'), ('med', 'Medical'), ('law', 'Law'), ('phrm', 'Pharmacy'), ('hmgmt', 'Hotel Management'), ('poly', 'Polytechnique')], max_length=30)),
                ('tier', models.CharField(choices=[('t1', 'Tier 1 - IITs, IIMs, and top institutes'), ('t2', 'Tier 2 - Popular colleges'), ('t3', 'Tier 3 - Local colleges and university')], max_length=50)),
                ('available_dates', models.CharField(choices=[('d1', 'This month'), ('d2', '1-3 months ahead'), ('d3', '3-6 months ahead'), ('d4', '6 months >')], max_length=30)),
                ('gender_ratio', models.CharField(choices=[('r1', 'High female population'), ('r2', 'High male population'), ('r3', '1:1 or nearby')], max_length=30)),
                ('purchasing_power', models.CharField(choices=[('p1', 'Very High'), ('p2', 'High'), ('p3', 'Medium'), ('p4', 'Low')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
