# Generated by Django 3.0.2 on 2020-02-02 22:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='available_dates',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('d1', 'This month'), ('d2', '1-3 months ahead'), ('d3', '3-6 months ahead'), ('d4', '6 months >')], max_length=30),
        ),
    ]
