# Generated by Django 3.0.2 on 2020-02-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200202_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.College')),
            ],
        ),
    ]
