# Generated by Django 3.0.2 on 2020-02-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='csrf_token',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
